version: '3.8'

services:
  ReactApp:
    build: ./ReactApp
    context: ./client
    dockerfile: Dockerfile
    ports:
      - "80:80"
      - "3000:3000"
    depends_on:
      - CSharpService
      - flaskDB
    networks:
      - mother-web

  CSharpService:
    build:
      context: ./server/CSharpService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=${DATABASE_URL}
    ports:
      - "5001:80"

  flaskDB:
    build: ./flaskDB
    context: ./server/flaskDB
    dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
      - "3000:3000"
    networks:
      - motherweb-net

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    context: ./nginx
    dockerfile: /Dockerfile
    ports:
      - "443:443"
      - "80:80"
      - "5000:5000"
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flaskDB
      - CSharpService
      - ReactApp
    networks:
      - motherweb-net

  networks:
    motherweb-net:
      - bridge

volumes:
  postgres_data:
