services:
  ReactApp:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: motherwebnet-reactapp
    ports:
      - "80:80"
      - "3000:3000"
    depends_on:
      - flaskDB
    networks:
      - motherweb-net
    volumes:
      - ./client:/app

  flaskDB:
    build:
      context: ./server/flaskDB
      dockerfile: Dockerfile
    image: motherwebnet-flaskdb
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    networks:
      - motherweb-net
    volumes:
      - ./server/flaskDB:/app
      - postgres_data:/var/lib/postgresql/data

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - type: bind
        source: ./db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "8080:80"
      - "3001:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flaskDB
      - ReactApp
      - db
    networks:
      - motherweb-net

networks:
  motherweb-net:
    driver: bridge

volumes:
  postgres_data: